---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: gce-disk-1
spec:
  capacity:
    storage: "10Gi"
  accessModes:
    - "ReadWriteOnce"
  mountOptions:
    - hard
    - nolock
    - nfsvers=3
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "gce-disk-1
