apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
  - name: webapp
    image: kubeguide/tomcat-app:v1
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: app-logs
      mountPath: /usr/local/tomcat/logs
  # log collector sidecar
  - name: fluentd
    image: fluent/fluentd:v1.9.2-1.0
    volumeMounts:
    - name: app-logs
      mountPath: /app-logs
    - name: config-volume
      mountPath: /etc/fluent/config.d
  volumes:
  - name: app-logs
    emptyDir: {}
  - name: config-volume
    configMap:
      name: fluentd-config
